services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - SYS_NICE
    ports:
      - "11434:11434"
    volumes:
      - ./data:/root/.ollama
    environment:
      - OLLAMA_LOAD_TIMEOUT=60m
    read_only: true

volumes:
  ollama:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data